### ISSUE TITLE
When access ssh for first time, prompt to add fingerprint to known hosts 

### ISSUE THREAD

**Issue by liza-mae** [sqren/backport#45] opened 2018-01-31 23:35 UTC
Backport tool uses ssh which prompted me to accept the new fingerprint and add it to my known hosts which paused/waited because stderr/stdout is not properly being displayed. 

It should fail or prompt me to accept the fingerprint?

@spalger

**Comment by sqren** [comment] 2018-02-01 13:44
Hi @liza-mae, thanks for making me aware of this. I just tried to delete my `known_hosts` file and was able to reproduce the issue, and was getting this error

```
The authenticity of host 'github.com (192.30.253.113)' can't be established.
RSA key fingerprint is <fingerprint>.
```

it should also output this part, and wait for user input (but it doesn't)
```
Are you sure you want to continue connecting (yes/no)?
```

I was not even considering this case. Is is because you have not before interacted with github over ssh? Do you normally use password authentication instead of ssh?
It occurs to me, that some users might not even use ssh - so apart from being able to setup ssh on first-time use, it should ask whether to use ssh or password, right?

**Comment by epixa** [comment] 2018-02-01 15:24
@sqren I recommend encouraging best practices (ssh) through this tool rather than supporting other use cases (passwords) just because they exist. You could always add the password stuff if there was enough demand for it.

**Comment by sqren** [comment] 2018-02-01 15:26
@epixa That's a good point. I was not looking forward to supporting several authentication mechanisms.

**Comment by sqren** [comment] 2018-03-13 19:23
@liza-mae were you able to solve your problem by adding github.com to you known hosts before running `backport`? `ssh github.com` should do the trick.

**Comment by liza-mae** [comment] 2018-03-13 19:27
Hi @sqren , yes that did work for me.  Thanks.

**Comment by sqren** [comment] 2018-03-13 20:34
Good to hear!
Closing in favor of https://github.com/sqren/backport/issues/56

**Closed by sqren** 2018-03-13 20:34 UTC
